import type {
  Assessment,
  Component,
  DataFlow,
  EvidenceItem,
  Finding,
  PostureSnapshot,
  RemediationTask,
  ReportSection,
  ScopeItem,
  TestCheck,
  TrustBoundary,
} from "../types";

export const assessment: Assessment = {
  id: "WM-SA-2026-01",
  name: "World Monitor Security Assurance Review",
  target: "https://www.worldmonitor.app",
  sourceRepo: "https://github.com/koala73/worldmonitor",
  status: "in-progress",
  startDate: "2026-09-14",
  endDate: "2026-10-09",
  leadAssessor: "SIH 2026 assessment cell",
  authorizationRef: "RoE-WM-2026-01 demo authorization",
  objective:
    "Assess authentication, authorization, API, cache, client-side, MCP/OAuth, desktop sidecar and data-handling controls using production-safe methods and local proof-of-concept fixtures.",
};

export const scope: ScopeItem[] = [
  {
    id: "S-01",
    asset: "worldmonitor.app browser dashboard",
    kind: "web",
    inScope: true,
    notes:
      "Passive observation only on live service; active checks use local fixtures.",
  },
  {
    id: "S-02",
    asset: "Vercel Edge API routes",
    kind: "api",
    inScope: true,
    notes: "Source review, route inventory and local harness checks.",
  },
  {
    id: "S-03",
    asset: "Anonymous wm-session and API-key validation",
    kind: "auth",
    inScope: true,
    notes: "Header, cookie and force-key precedence review.",
  },
  {
    id: "S-04",
    asset: "Premium RPC authorization paths",
    kind: "auth",
    inScope: true,
    notes: "Coverage review against public and premium route lists.",
  },
  {
    id: "S-05",
    asset: "MCP and OAuth agent surface",
    kind: "mcp",
    inScope: true,
    notes: "Protocol and authorization-state review with safe local mocks.",
  },
  {
    id: "S-06",
    asset: "Tauri desktop sidecar",
    kind: "desktop",
    inScope: true,
    notes: "Loopback boundary and secret injection review.",
  },
  {
    id: "S-07",
    asset: "RSS, YouTube, webhook and proxy-like endpoints",
    kind: "api",
    inScope: true,
    notes: "SSRF and allowlist review; no live internal probing.",
  },
  {
    id: "S-08",
    asset: "Third-party providers",
    kind: "third-party",
    inScope: false,
    notes:
      "Provider systems excluded; only World Monitor handling is assessed.",
  },
  {
    id: "S-09",
    asset: "Cloud provider control planes",
    kind: "infra",
    inScope: false,
    notes: "Vercel, Clerk, Convex, Railway and Upstash platforms are excluded.",
  },
];

export const boundaries: TrustBoundary[] = [
  {
    id: "client",
    name: "Browser",
    description: "Untrusted user-controlled runtime.",
    x: 24,
    y: 54,
    w: 245,
    h: 242,
  },
  {
    id: "local",
    name: "Workstation",
    description: "Semi-trusted desktop and loopback services.",
    x: 24,
    y: 330,
    w: 245,
    h: 238,
  },
  {
    id: "edge",
    name: "Edge API",
    description: "Trusted request enforcement boundary.",
    x: 315,
    y: 54,
    w: 255,
    h: 300,
  },
  {
    id: "agent",
    name: "MCP/OAuth",
    description: "Delegated agent access boundary.",
    x: 315,
    y: 390,
    w: 255,
    h: 178,
  },
  {
    id: "managed",
    name: "Identity",
    description: "Managed auth and billing state.",
    x: 620,
    y: 54,
    w: 255,
    h: 178,
  },
  {
    id: "backend",
    name: "Data Plane",
    description: "Cache, jobs, storage and ingested data.",
    x: 620,
    y: 268,
    w: 255,
    h: 300,
  },
  {
    id: "external",
    name: "External",
    description: "Untrusted sources and callers.",
    x: 925,
    y: 54,
    w: 235,
    h: 514,
  },
];

export const components: Component[] = [
  {
    id: "spa",
    name: "Browser SPA",
    short: "SPA",
    kind: "Dashboard client",
    zone: "client",
    exposure: "public",
    description:
      "Renders maps, panels, feeds and source-attributed intelligence.",
    dataHandled: ["session state", "feed content", "preferences"],
    x: 146,
    y: 168,
  },
  {
    id: "sidecar",
    name: "Desktop sidecar",
    short: "Sidecar",
    kind: "Tauri local API bridge",
    zone: "local",
    exposure: "local",
    description:
      "Local process that proxies API calls and injects workstation-held secrets.",
    dataHandled: ["local secrets", "API responses"],
    x: 146,
    y: 452,
  },
  {
    id: "edge-api",
    name: "Edge API gateway",
    short: "Gateway",
    kind: "Vercel Edge functions",
    zone: "edge",
    exposure: "public",
    description:
      "Applies CORS, API key validation, rate limits, cache headers and route dispatch.",
    dataHandled: ["API keys", "anonymous sessions", "premium decisions"],
    x: 442,
    y: 164,
  },
  {
    id: "edge-cache",
    name: "Cache and headers",
    short: "Cache",
    kind: "HTTP cache policy",
    zone: "edge",
    exposure: "public",
    description:
      "Controls shared cacheability, Vary semantics and no-store paths.",
    dataHandled: ["public datasets", "auth denials"],
    x: 442,
    y: 282,
  },
  {
    id: "mcp",
    name: "MCP server",
    short: "MCP",
    kind: "Agent protocol endpoint",
    zone: "agent",
    exposure: "authenticated",
    description:
      "Exposes tools through OAuth/API-key authenticated model clients.",
    dataHandled: ["delegated tokens", "tool results"],
    x: 442,
    y: 480,
  },
  {
    id: "clerk",
    name: "Clerk auth",
    short: "Clerk",
    kind: "Managed identity",
    zone: "managed",
    exposure: "authenticated",
    description: "Issues user identity evidence for web sessions.",
    dataHandled: ["identity tokens", "user id"],
    x: 747,
    y: 126,
  },
  {
    id: "convex",
    name: "Convex state",
    short: "Convex",
    kind: "Managed backend",
    zone: "backend",
    exposure: "internal",
    description: "Stores entitlements, user state, keys and workflow data.",
    dataHandled: ["entitlements", "user state", "API keys"],
    x: 747,
    y: 336,
  },
  {
    id: "redis",
    name: "Upstash Redis",
    short: "Redis",
    kind: "Cache and rate-limit state",
    zone: "backend",
    exposure: "internal",
    description:
      "Holds cached datasets, seed metadata, locks and limiter counters.",
    dataHandled: ["cache rows", "rate keys"],
    x: 747,
    y: 456,
  },
  {
    id: "railway",
    name: "Railway jobs",
    short: "Jobs",
    kind: "Ingestion workers",
    zone: "backend",
    exposure: "internal",
    description: "Fetches external sources and publishes read models.",
    dataHandled: ["provider responses", "derived cohorts"],
    x: 747,
    y: 536,
  },
  {
    id: "sources",
    name: "External sources",
    short: "Sources",
    kind: "News, markets, aviation, maritime",
    zone: "external",
    exposure: "public",
    description: "Untrusted source material and upstream provider APIs.",
    dataHandled: ["untrusted content", "provider metadata"],
    x: 1042,
    y: 282,
  },
  {
    id: "attackers",
    name: "External callers",
    short: "Caller",
    kind: "Internet clients",
    zone: "external",
    exposure: "public",
    description:
      "Browsers, scripts, crawlers and agent clients outside operator control.",
    dataHandled: ["crafted requests"],
    x: 1042,
    y: 142,
  },
];

export const dataFlows: DataFlow[] = [
  {
    id: "F-01",
    from: "spa",
    to: "edge-api",
    label: "/api/* fetch",
    protocol: "HTTPS",
    crossesBoundary: true,
    carriesSecrets: true,
  },
  {
    id: "F-02",
    from: "edge-api",
    to: "clerk",
    label: "JWT/session evidence",
    protocol: "HTTPS",
    crossesBoundary: true,
    carriesSecrets: true,
  },
  {
    id: "F-03",
    from: "edge-api",
    to: "convex",
    label: "entitlements and keys",
    protocol: "HTTPS",
    crossesBoundary: true,
    carriesSecrets: true,
  },
  {
    id: "F-04",
    from: "edge-api",
    to: "redis",
    label: "cache/limit lookup",
    protocol: "HTTPS",
    crossesBoundary: true,
    carriesSecrets: false,
  },
  {
    id: "F-05",
    from: "railway",
    to: "sources",
    label: "scheduled ingestion",
    protocol: "HTTPS/RSS",
    crossesBoundary: true,
    carriesSecrets: false,
  },
  {
    id: "F-06",
    from: "mcp",
    to: "edge-api",
    label: "tool call gateway",
    protocol: "JSON-RPC",
    crossesBoundary: true,
    carriesSecrets: true,
  },
  {
    id: "F-07",
    from: "sidecar",
    to: "edge-api",
    label: "desktop fallback",
    protocol: "HTTPS",
    crossesBoundary: true,
    carriesSecrets: true,
  },
  {
    id: "F-08",
    from: "attackers",
    to: "edge-api",
    label: "untrusted request",
    protocol: "HTTPS",
    crossesBoundary: true,
    carriesSecrets: false,
  },
];

export const evidence: EvidenceItem[] = [
  {
    id: "E-01",
    title: "Mixed browser, API, MCP and desktop surfaces",
    kind: "observation",
    source: "Repository architecture documentation",
    accessedAt: "2026-09-27",
    observation:
      "World Monitor combines a browser dashboard, Vercel Edge API functions, MCP/OAuth endpoints, Convex, Redis, Railway jobs and a Tauri desktop sidecar.",
    confidence: 5,
    limitation: "Source documentation may lag deployment configuration.",
    classification: "TLP:CLEAR",
    verification: "verified",
    findingIds: ["FND-01", "FND-02"],
    origin: "seed",
  },
  {
    id: "E-02",
    title: "Anonymous wms_ session is explicitly not user-bound",
    kind: "observation",
    source: "api/_api-key.js source review",
    accessedAt: "2026-09-27",
    observation:
      "Comments and logic state that anonymous session tokens are freely mintable and must be rejected when forceKey=true.",
    confidence: 5,
    limitation:
      "This dashboard records the design risk; exploitation requires route-specific validation.",
    classification: "TLP:CLEAR",
    verification: "verified",
    findingIds: ["FND-01"],
    origin: "seed",
  },
  {
    id: "E-03",
    title: "Shared cache policy is a sensitive control",
    kind: "observation",
    source: "Architecture and gateway source review",
    accessedAt: "2026-09-27",
    observation:
      "The gateway distinguishes public cacheable responses, credentialed responses and auth denials, with comments warning about cached ACAO and no-store behaviour.",
    confidence: 4,
    limitation: "Live CDN behaviour is not modified by this assessment.",
    classification: "TLP:CLEAR",
    verification: "verified",
    findingIds: ["FND-02"],
    origin: "seed",
  },
  {
    id: "E-04",
    title: "HTML rendering uses audited safe and unsafe paths",
    kind: "observation",
    source: "src/utils/sanitize.ts and component grep",
    accessedAt: "2026-09-27",
    observation:
      "The codebase contains safeHtml, sanitizeUrl and unsafeRawHtml helpers plus many legacy direct HTML rendering migrations.",
    confidence: 4,
    limitation:
      "Manual review is needed to prove individual sinks exploitable.",
    classification: "TLP:CLEAR",
    verification: "verified",
    findingIds: ["FND-03"],
    origin: "seed",
  },
  {
    id: "E-05",
    title: "Proxy-like endpoints exist",
    kind: "observation",
    source: "api directory inventory",
    accessedAt: "2026-09-27",
    observation:
      "RSS, YouTube, webhook, notification and reverse-geocode endpoint families create URL and source-handling review requirements.",
    confidence: 4,
    limitation: "No live SSRF payloads were sent.",
    classification: "TLP:CLEAR",
    verification: "verified",
    findingIds: ["FND-04"],
    origin: "seed",
  },
  {
    id: "E-06",
    title: "Production dependency audit is clean",
    kind: "observation",
    source: "npm audit --omit=dev",
    accessedAt: "2026-09-27",
    observation:
      "The current application lockfile reports zero known production dependency advisories.",
    confidence: 5,
    limitation:
      "Audit results are time-bound and do not establish that every dependency path is reachable or secure.",
    classification: "TLP:CLEAR",
    verification: "verified",
    findingIds: ["FND-05"],
    origin: "seed",
  },
];

export const findings: Finding[] = [
  {
    id: "FND-01",
    title:
      "Premium RPC authorization coverage can drift from anonymous session rules",
    summary:
      "Routes that forget force-key or premium-path registration may accept freely mintable anonymous session credentials.",
    description:
      "The design correctly rejects anonymous wms_ credentials when a route demands forceKey=true. The residual risk is coverage drift: new premium RPCs or high-cost endpoints can be added without being listed in the premium path registry or without route-level entitlement tests.",
    componentId: "edge-api",
    owasp: "A01:2021 Broken Access Control",
    cwe: "CWE-862",
    cvss: {
      AV: "N",
      AC: "L",
      PR: "N",
      UI: "N",
      S: "U",
      C: "H",
      I: "L",
      A: "L",
    },
    status: "open",
    verification: "demo",
    likelihood: 3,
    impact: 5,
    evidenceIds: ["E-01", "E-02"],
    checkIds: ["CHK-01", "CHK-02"],
    stepsToReproduce: [
      "Run the local premium-route coverage check.",
      "Review any route marked high-cost or premium that is absent from the protected registry.",
      "Confirm the route rejects anonymous wms_ credentials in a local test.",
    ],
    safePoc:
      "The harness uses a local route fixture containing one intentionally unregistered premium route and verifies that anonymous session acceptance is reported without touching production.",
    businessImpact:
      "A real drift instance could expose paid intelligence, generate unbounded provider cost, or allow anonymous callers to reach analyst workflows intended for subscribers.",
    remediation: [
      "Generate premium-route tests from the source of truth.",
      "Fail CI when a premium handler lacks entitlement coverage.",
      "Require forceKey=true or Clerk entitlement checks for all spend-bearing routes.",
    ],
    retest: {
      status: "not-retested",
      notes: "Awaiting engineering registry coverage.",
    },
    createdAt: "2026-09-27",
    updatedAt: "2026-09-27",
  },
  {
    id: "FND-02",
    title:
      "Credential-dependent responses require strict no-store and Vary guarantees",
    summary:
      "Cache and CORS mistakes around auth denials or session-bearing requests can become cross-user data leakage.",
    description:
      "The gateway contains explicit controls for public versus credentialed cache behaviour. Because the application mixes anonymous sessions, API keys, premium paths and shared CDN caches, this should be continuously tested as a security invariant.",
    componentId: "edge-cache",
    owasp: "A05:2021 Security Misconfiguration",
    cwe: "CWE-525",
    cvss: {
      AV: "N",
      AC: "H",
      PR: "L",
      UI: "N",
      S: "C",
      C: "H",
      I: "L",
      A: "N",
    },
    status: "in-remediation",
    verification: "demo",
    likelihood: 3,
    impact: 4,
    evidenceIds: ["E-01", "E-03"],
    checkIds: ["CHK-03"],
    stepsToReproduce: [
      "Run the cache invariant fixture.",
      "Inspect simulated credentialed responses for Cache-Control, CDN-Cache-Control and Vary.",
      "Confirm public cache headers are only emitted for public data.",
    ],
    safePoc:
      "The harness evaluates response header fixtures and blocks active network cache poisoning tests in production-safe mode.",
    businessImpact:
      "Incorrect cache headers can disclose user-specific data, authentication state, or premium denial details to a different caller.",
    remediation: [
      "Create contract tests for every credential-bearing endpoint.",
      "Default auth failures and user-specific responses to private/no-store.",
      "Keep public cache helper usage behind an explicit allowlist.",
    ],
    retest: {
      status: "partial",
      notes:
        "Core gateway controls exist; route-level inventory needs ongoing proof.",
    },
    createdAt: "2026-09-27",
    updatedAt: "2026-09-27",
  },
  {
    id: "FND-03",
    title: "Large HTML rendering surface needs sink-level XSS regression tests",
    summary:
      "Feed and map UI renders source-controlled text through many HTML composition paths.",
    description:
      "The codebase has sanitization helpers and audited unsafe rendering wrappers, which is positive. The residual risk is a future component interpolating external feed content into HTML without escapeHtml or sanitizeUrl.",
    componentId: "spa",
    owasp: "A03:2021 Injection",
    cwe: "CWE-79",
    cvss: {
      AV: "N",
      AC: "L",
      PR: "N",
      UI: "R",
      S: "C",
      C: "L",
      I: "L",
      A: "N",
    },
    status: "open",
    verification: "demo",
    likelihood: 4,
    impact: 3,
    evidenceIds: ["E-04"],
    checkIds: ["CHK-04"],
    stepsToReproduce: [
      "Run the local XSS fixture check.",
      "Inject the provided harmless payload into mock feed fields.",
      "Verify rendered output contains escaped text rather than executable HTML.",
    ],
    safePoc:
      "The PoC uses a non-executing sentinel payload in a local string renderer and checks for escaped output.",
    businessImpact:
      "A confirmed XSS could allow session actions in the browser context, UI manipulation, phishing overlays, or source-trust erosion.",
    remediation: [
      "Ban raw innerHTML except through reviewed wrappers.",
      "Add component-level tests for external feed fields.",
      "Require sanitizeUrl for every source-provided link.",
    ],
    retest: {
      status: "not-retested",
      notes: "Needs sink inventory automation.",
    },
    createdAt: "2026-09-27",
    updatedAt: "2026-09-27",
  },
  {
    id: "FND-04",
    title: "Proxy-like endpoint allowlists need parser-consistency tests",
    summary:
      "RSS, YouTube, webhook and URL-handling routes should reject private network and parser-bypass URLs.",
    description:
      "The repository includes endpoints that process remote URLs or relay upstream content. These are common SSRF and open-proxy risk areas unless allowlists, protocol restrictions and redirects are consistently enforced.",
    componentId: "edge-api",
    owasp: "A10:2021 Server-Side Request Forgery",
    cwe: "CWE-918",
    cvss: {
      AV: "N",
      AC: "L",
      PR: "L",
      UI: "N",
      S: "U",
      C: "H",
      I: "L",
      A: "L",
    },
    status: "open",
    verification: "demo",
    likelihood: 3,
    impact: 4,
    evidenceIds: ["E-05"],
    checkIds: ["CHK-05"],
    stepsToReproduce: [
      "Run the local URL policy fixture.",
      "Review rejected localhost, link-local and credentialed URL cases.",
      "Add endpoint-specific allowlist tests for every proxy-like route.",
    ],
    safePoc:
      "The harness checks URL strings against local policy code only; it never connects to internal hosts.",
    businessImpact:
      "A confirmed SSRF could expose metadata services, internal admin panels, or provider credentials reachable from serverless infrastructure.",
    remediation: [
      "Centralize URL validation.",
      "Block private IP ranges after DNS resolution.",
      "Reject redirects to disallowed hosts.",
      "Constrain every proxy route to a named allowlist.",
    ],
    retest: {
      status: "not-retested",
      notes: "Endpoint-by-endpoint validation pending.",
    },
    createdAt: "2026-09-27",
    updatedAt: "2026-09-27",
  },
  {
    id: "FND-05",
    title: "Dependency posture requires continuous verification",
    summary:
      "The current production audit is clean, but dependency drift still requires automated monitoring and reachability review.",
    description:
      "The current lockfile reports zero known production advisories. This candidate tracks the residual supply-chain risk: future upgrades can introduce advisories, and automated audit results do not replace runtime reachability analysis.",
    componentId: "spa",
    owasp: "A06:2021 Vulnerable and Outdated Components",
    cwe: "CWE-1104",
    cvss: {
      AV: "N",
      AC: "H",
      PR: "N",
      UI: "R",
      S: "U",
      C: "N",
      I: "N",
      A: "H",
    },
    status: "open",
    verification: "demo",
    likelihood: 1,
    impact: 3,
    evidenceIds: ["E-06"],
    checkIds: ["CHK-06"],
    stepsToReproduce: [
      "Run npm audit --omit=dev.",
      "Map each advisory to the importing package and runtime path.",
      "Document whether untrusted user files can reach the vulnerable parser.",
    ],
    safePoc:
      "No exploit payload is used. CI executes the production dependency audit and fails when npm reports a known advisory.",
    businessImpact:
      "Unmonitored dependency drift can introduce denial-of-service, data exposure or emergency-upgrade risk after an otherwise clean release.",
    remediation: [
      "Pin or override fixed versions when available.",
      "Document non-reachable advisories with expiry dates.",
      "Add dependency audit and SBOM generation to CI.",
    ],
    retest: {
      status: "pass",
      notes:
        "Current production audit reports zero advisories; continuous CI monitoring remains required.",
    },
    createdAt: "2026-09-27",
    updatedAt: "2026-09-27",
  },
];

export const checks: TestCheck[] = [
  {
    id: "CHK-01",
    category: "auth",
    title: "Anonymous session rejected on premium fixtures",
    objective:
      "Ensure freely mintable wms_ credentials cannot authorize premium/spend-bearing routes.",
    componentId: "edge-api",
    mode: "fixture",
    asvs: "ASVS 2.1 / 4.1",
    relatedFindingIds: ["FND-01"],
  },
  {
    id: "CHK-02",
    category: "authz",
    title: "Premium route registry coverage",
    objective:
      "Detect high-cost RPC fixtures missing from protected path registry.",
    componentId: "edge-api",
    mode: "fixture",
    asvs: "ASVS 4.1.3",
    relatedFindingIds: ["FND-01"],
  },
  {
    id: "CHK-03",
    category: "cors",
    title: "Credentialed response cache invariants",
    objective:
      "Verify credential-bearing and auth-denial responses are no-store/private and vary on credentials.",
    componentId: "edge-cache",
    mode: "fixture",
    asvs: "ASVS 14.4",
    relatedFindingIds: ["FND-02"],
  },
  {
    id: "CHK-04",
    category: "xss",
    title: "Source text rendering escapes HTML sentinels",
    objective:
      "Confirm untrusted feed titles render as text in local fixtures.",
    componentId: "spa",
    mode: "active-local",
    asvs: "ASVS 5.3",
    relatedFindingIds: ["FND-03"],
  },
  {
    id: "CHK-05",
    category: "ssrf",
    title: "Proxy URL policy rejects private targets",
    objective:
      "Reject localhost, link-local, private ranges and credentialed URLs before fetch.",
    componentId: "edge-api",
    mode: "active-local",
    asvs: "ASVS 5.2 / 13.1",
    relatedFindingIds: ["FND-04"],
  },
  {
    id: "CHK-06",
    category: "deps",
    title: "Production dependency advisory triage",
    objective: "Import npm audit findings and classify runtime reachability.",
    componentId: "spa",
    mode: "fixture",
    asvs: "ASVS 14.2",
    relatedFindingIds: ["FND-05"],
  },
  {
    id: "CHK-07",
    category: "mcp",
    title: "MCP tool auth wall present",
    objective:
      "Authenticated tools require OAuth or user API key in local protocol fixtures.",
    componentId: "mcp",
    mode: "fixture",
    asvs: "ASVS 2.2 / 13.2",
    relatedFindingIds: [],
  },
  {
    id: "CHK-08",
    category: "desktop",
    title: "Sidecar loopback requires bearer proof",
    objective:
      "Desktop-local API fixture rejects cross-origin loopback calls without a signed proof.",
    componentId: "sidecar",
    mode: "active-local",
    asvs: "ASVS 14.5",
    relatedFindingIds: [],
  },
];

export const remediationTasks: RemediationTask[] = [
  {
    id: "R-01",
    title: "Generate auth coverage tests from route inventory",
    detail:
      "Fail CI if a spend-bearing or premium RPC lacks force-key/entitlement coverage.",
    phase: "guardrail",
    findingIds: ["FND-01"],
    owner: "API platform",
    effort: "M",
    targetWeek: 1,
    status: "in-progress",
  },
  {
    id: "R-02",
    title: "Create cache contract matrix",
    detail:
      "Assert Cache-Control, CDN-Cache-Control and Vary values for public, session, Pro and error responses.",
    phase: "regression",
    findingIds: ["FND-02"],
    owner: "Edge runtime",
    effort: "M",
    targetWeek: 1,
    status: "todo",
  },
  {
    id: "R-03",
    title: "Add sink-level render tests",
    detail:
      "Feed every external text/link field through harmless HTML sentinels and verify escaped rendering.",
    phase: "engineering",
    findingIds: ["FND-03"],
    owner: "Frontend",
    effort: "L",
    targetWeek: 2,
    status: "todo",
  },
  {
    id: "R-04",
    title: "Centralize URL fetch policy",
    detail:
      "Use one parser-consistent validator for proxy-like routes and block private network redirects.",
    phase: "quick-win",
    findingIds: ["FND-04"],
    owner: "API platform",
    effort: "M",
    targetWeek: 1,
    status: "todo",
  },
  {
    id: "R-05",
    title: "Publish SBOM and reachability notes",
    detail:
      "Classify npm audit advisories and include accepted-risk expiry dates.",
    phase: "guardrail",
    findingIds: ["FND-05"],
    owner: "Security",
    effort: "S",
    targetWeek: 1,
    status: "todo",
  },
];

export const reportSections: ReportSection[] = [
  { key: "executive", title: "Executive Summary", included: true },
  { key: "scope", title: "Scope and Rules of Engagement", included: true },
  { key: "methodology", title: "Methodology", included: true },
  { key: "findings", title: "Technical Findings", included: true },
  { key: "matrix", title: "Risk Matrix", included: true },
  { key: "roadmap", title: "Remediation Roadmap", included: true },
  { key: "appendix", title: "Evidence Appendix", included: true },
];

export const posture: PostureSnapshot[] = [
  { label: "Scoping", score: 42, open: 0 },
  { label: "Discovery", score: 56, open: 5 },
  { label: "Validation", score: 64, open: 4 },
  { label: "Remediation", score: 78, open: 3 },
];
